os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

branches:
  only:
  - master

addons:
  apt:
    packages:
    - sshpass
    
script:
- set -e
- .travis/build_docker_image.sh
->
  if [ "$TRAVIS_PULL_REQUEST" = "false" ];
    bash .travis/push_image_to_dockerhub.sh;
    bash .travis/deploy.sh;
  fi